export const item=[1,2,3,4,5,6,7,8,910,12,45,21,54]

export const name=[
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'one'},
    {message:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type'},
    {message:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type'},
  ]